##
##  Makefile -- Build procedure for sample secuip Apache module
##  Autogenerated via ``apxs -n secuip -g''.
##

builddir=.
top_srcdir=/app/apache
top_builddir=/app/apache
include /app/apache/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_secuip.o mod_secuip.lo mod_secuip.slo mod_secuip.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/secuip

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

